### ISSUE TITLE
Create multi-arch docker file

### ISSUE THREAD

**Issue by fangohr** [fangohr/octopus-in-docker#12]
Currently, we only have a x86 image at DockerHub. Ideally, this wolud be a multi-architecture image so that M1/M2 users would pull the right image automatically.

Some useful pointers are at https://medium.com/@life-is-short-so-enjoy-it/docker-how-to-build-and-push-multi-arch-docker-images-to-docker-hub-64dea4931df9

**Comment by iamashwin99** [comment]
Done in #13
