### ISSUE TITLE
Update octopus buildscript - LDLIBRARYPATH

### ISSUE THREAD

**Issue by iamashwin99** [fangohr/octopus-in-docker#24]
Since the update of octopus 14,
we have the problems from "develop" now in stable.
( like the one with libsym  #9 )
We need to decide how to handle this in the build script, two options:
- move it to general for all builds ( breaks for versions older than 14)
- conditionally do the tests and keep the backward compatibility ( harder to maintain)

**Comment by fangohr** [comment]
Thanks for picking this up. I'd like to review this with Henning at some point to better understand where–in an ideal world–this should be fixed.

**Comment by fangohr** [comment]
Closed by #26
