### ISSUE TITLE
Update base image to debian:bookworm

### ISSUE THREAD

**Issue by lang-m** [fangohr/octopus-in-docker#4]
Problem: The pandoc version in debian:bullseye (2.9.2.1) is a bit old and Sphinx (in postopus) warns that this version is not officially supported  (minimum is 2.14.2) The version in bookworm (2.17.1.1) would be sufficiently new.

**Comment by fangohr** [comment]
That is resolved now, we use `bookworm` as the base image (https://github.com/fangohr/octopus-in-docker/blob/0d9aecadec908e8bdc019ac33950d8a8a593344c/Dockerfile#L1).

**Comment by jasonleekungfu** [comment]
Hi! Have you considered using Ubuntu 22.04? The primary reason is for GPU support. NVidia officially supports Ubuntu-based CUDA containers, which can be directly used as base image to build GPU-compatible Octopus containers and without much changes to the Debian-based installation commands.
